modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/ProjectEssentials/ProjectEssentials-Cooldown/issues"

[[mods]]
    modId="project_essentials_cooldown"
    version="1.15.2-1.0.2"
    displayName="Project Essentials Cooldown"
    updateJSONURL="https://raw.githubusercontent.com/ProjectEssentials/ProjectEssentials-Cooldown/MC-1.15.2/update.json"
    displayURL="https://github.com/ProjectEssentials/ProjectEssentials-Cooldown"
    credits="Thanks JetBrains for Intellij IDEA license!"
    authors="MairwunNx (Pavel Erokhin)"
    description='''
    Project Essentials Cooldown - additional module for Essentials;
    Just controlling player command spamming.

    Also it just command cooldown API for forge.
    '''

[[dependencies.projectessentialscooldown]]
    modId="project_essentials_core"
    mandatory=true
    versionRange="[1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.projectessentialscooldown]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.projectessentialscooldown]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
